the-mashmake-blog/config/routes.rb
Rails.application.routes.draw do
  scope '/learn/udemy-alpha-blog' do
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'pages#home'
    get 'about', to: 'pages#about'
    resources :articles # expects predefined methods in the ArticlesController to exist. Methods are: new, create, edit, update, delete and index
    get 'signup', to: 'users#new'
    resources :users, except: [:new]
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
    resources :categories
  end
end

the-mashmake-blog/app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="flex-shrink-0 py-4 bg-dark text-white">
    <div class="container text-center">
        <small>Copyright &copy; <%= link_to "Mashmake", "/", class: "text-white" %></small>
    </div>
</footer>

the-mashmake-blog/app/views/layouts/_messages.html.erb
<% if flash[:notice]%>
  
  <%
    divClass = ''
    isSuccess = false
    isError = false
    
    if flash[:notice]['successMessage']
      isSuccess = true
      divClass = "alert alert-success alert-dismissible fade show"
    elsif flash[:notice]['errorMessages']
      isError = true
      divClass = "alert alert-danger alert-dismissible fade show"
    end
  %>
  
  <div class="<%= divClass %>" role="alert">
    <% if isSuccess %>
      <%= flash[:notice]['successMessage'] %>
    <% elsif isError %>
      <ul>
      <% flash[:notice]['errorMessages'].each do |msg| %>
          <li><%= msg %></li>
      <% end %>
      </ul>
    <% end %>
    
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  
<% end %>

the-mashmake-blog/app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to "MASHMAKE", root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          
          <% if logged_in? %>
            <li class="nav-item">
              <%= link_to 'Bloggers', users_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Categories', categories_path, class: "nav-link" %>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Articles
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to 'Create New Article', new_article_path, class: "dropdown-item" %>
                <%= link_to 'View All', articles_path, class: "dropdown-item" %>
                <!--<div class="dropdown-divider"></div>-->
                <!--<a class="dropdown-item" href="#">Something else here</a>-->
              </div>
            </li>
          <% end %>
        </ul>
        
        <% if logged_in? %>
          <div class="dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarProfileDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= gravatar_for(current_user.email, {size: 20}) %> <%= current_user.username %> <%= "(Admin)" if current_user.admin? %>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarProfileDropdown">
              <%= link_to 'Profile', user_path(current_user), class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to 'Logout', logout_path, class: "dropdown-item", method: :delete %>
            </div>
          </div>
        <% else %>
          <%= link_to 'Login', login_path, class: "nav-link" %>
          <%= link_to 'Sign Up!', signup_path, class: "nav-link" %>
        <% end %>
        
        <!--<form class="form-inline my-2 my-lg-0">-->
        <!--  <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">-->
        <!--  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
        <!--</form>-->
    </div>
</nav>

the-mashmake-blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Mashmake Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body class="d-flex flex-column">
    
    <%= render 'layouts/navigation' %>
    
    <div id="page-content">
      <% 
      # Partials are prefixed with underscore but to access them, `layouts` must be specified in the path (even though the current file)
      #    is relative. Also, no need for the underscore when referring to the partial
      %>
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    
    <%= render 'layouts/footer' %>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>    
  </body>
</html>