the-mashmake-blog/config/routes.rb
Rails.application.routes.draw do
  scope '/learn/udemy-alpha-blog' do
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'pages#home'
    get 'about', to: 'pages#about'
    resources :articles # expects predefined methods in the ArticlesController to exist. Methods are: new, create, edit, update, delete and index
    get 'signup', to: 'users#new'
    resources :users, except: [:new]
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
    resources :categories
  end
end

the-mashmake-blog/app/models/category.rb
class Category < ApplicationRecord
    has_many :article_categories
    has_many :articles, through: :article_categories
    
    validates :name,
        presence: true,
        uniqueness: {case_sensitive: false},
        length: { minimum: 3, maximum: 25 }
end

the-mashmake-blog/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :set_category, except: [:index, :new, :create]
    before_action :require_admin, except: [:index, :show]
    
    def index
        @categories = Category.paginate(page: params[:page], per_page: 5)
    end
    
    def show
        @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
    end
    
    def new
        @category = Category.new
    end
    
    def create
        @category = Category.new(category_params)
        if @category.save
            flash[:notice] = { successMessage: "Category was saved." }
            redirect_to categories_path
        else
            errorMessages = []
            
            @category.errors.full_messages.each do |msg|
                errorMessages.append("#{msg}")
            end

            flash[:notice] = { errorMessages: errorMessages }
            
            redirect_to new_category_path
        end
    end
    
    def edit
    end
    
    def update
        if @category.update(category_params)
            flash[:notice] = { successMessage: "Category was updated for Category ID: #{@category.id.to_s}" }
            redirect_to categories_path
        else
            errorMessages = []
            
            @category.errors.full_messages.each do |msg|
                errorMessages.append("#{msg} for Category ID: #{@category.id.to_s}")
            end

            flash[:notice] = { errorMessages: errorMessages }
            
            redirect_to edit_category_path
        end
    end
    
    def destroy
        if @category.destroy
            flash[:notice] = { successMessage: "Successfully deleted the category." }
            redirect_to categories_path
        else
            errorMessages = []
            
            @category.errors.full_messages.each do |msg|
                errorMessages.append("#{msg}")
            end

            flash[:notice] = { errorMessages: errorMessages }
            
            redirect_to new_category_path
        end
    end
    
    private
    
    def category_params
        params.require(:category).permit(:name)
    end
    
    def set_category
        begin
            @category = Category.find(params[:id])
        rescue ActiveRecord::RecordNotFound => e
            flash[:notice] = { errorMessages: ["Category not found"] }
            redirect_to categories_path
        end
    end
    
    def require_admin
        if !(logged_in? && current_user.admin?)
            flash[:notice] = { errorMessages: ["Only admins can create/delete category"] }
            redirect_to categories_path
        end
    end
end

the-mashmake-blog/app/views/categories/_categories.html.erb
<div class="container">
    <table class="table table-hover bg-white">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
        <% @categories.each do |category| %>
            <tr>
                <th scope="row"><%=category.id%></th>
                <td><%=category.name%></td>
                <td>
                    <%= link_to 'View', category_path(category), class: "btn btn-primary btn-sm mr-3" %>
                    <% if logged_in? && current_user.admin? %>
                        <%= link_to 'Edit', edit_category_path(category), class: "btn btn-info btn-sm mr-3" %>
                        <%= link_to 'Delete', category_path(category), method: :delete, class: "btn btn-danger btn-sm", data: {confirm: "Are you sure?"} %>
                    <% end %>
                </td>
            </tr>
        <% end %>
         </tbody>
    </table>
    
    <% if logged_in? && current_user.admin? %>
    <div class="mb-4">
        <%= link_to 'Add Category', new_category_path, class: "btn btn-primary btn-sm" %>
    </div>
    <% end %>
    
    <% if @categories.count == 0 %>
      <div class="font-italic text-center">No categories found</div>
    <% end %>

    <div class="text-center">
        <%= will_paginate @categories, class: "apple_pagination" %>
    </div>
</div>

the-mashmake-blog/app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge badge-pill badge-info mr-1" %>

the-mashmake-blog/app/views/categories/_form.html.erb
<div class="container">
    
    <div class="row justify-content-center">
        <div class="col-12">
            <%= form_with(model: @category, class: "shadow p-5 mb-5 bg-white rounded", local: true) do |form| %>
                
                <div class="form-group row">
                    <%= form.label :name, "Category Name:", class: "col-sm-2 col-form-label" %>
                    <div class="col-sm-10">
                        <%= form.text_field :name, class: "form-control shadow rounded", placeholder: "Enter name", autofocus: true %>
                    </div>
                </div>
                
                <div class="form-group row justify-content-center">
                    <%= form.submit class: "btn btn-outline-primary"%>
                    &nbsp;&nbsp;&nbsp;
                    <%= link_to "Cancel", categories_path, class: "btn btn-outline-danger" %>
                </div>
                
            <% end %>
        </div>
    </div>
</div>

the-mashmake-blog/app/views/categories/edit.html.erb
<h1 class="text-center mt-4">Update Category ID: <%= @category.id %></h1>

<%= render 'form' %>

the-mashmake-blog/app/views/categories/index.html.erb
<h1 class="text-center mt-4">Categories</h1>

<%= render 'categories' %>

the-mashmake-blog/app/views/categories/new.html.erb
<h1 class="text-center mt-4">Create new category</h1>
<%= render 'form' %>

the-mashmake-blog/app/views/categories/show.html.erb
<h1 class="text-center mt-4">Category: <%= @category.name %></h1>
<div class="container">
    <table class="table table-hover bg-white">
        <caption>List of articles</caption>
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
        <% @category_articles.each do |article| %>
            <tr>
                <th scope="row"><%=article.id%></th>
                <td><%=article.title%></td>
                <td><%= link_to 'View', article_path(article), class: "btn btn-primary btn-sm" %></td>
            </tr>
        <% end %>
         </tbody>
    </table>
    
    <% if @category_articles.count == 0 %>
      <div class="font-italic text-center">No articles found</div>
    <% end %>

    <div class="text-center">
        <%= will_paginate @category_articles, class: "apple_pagination" %>
    </div>
</div>