the-mashmake-blog/config/routes.rb
Rails.application.routes.draw do
  scope '/learn/udemy-alpha-blog' do
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'pages#home'
    get 'about', to: 'pages#about'
    resources :articles # expects predefined methods in the ArticlesController to exist. Methods are: new, create, edit, update, delete and index
    get 'signup', to: 'users#new'
    resources :users, except: [:new]
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
    resources :categories
  end
end

the-mashmake-blog/app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories
    
    validates :title, 
        presence: true, 
        length: { minimum: 1, maximum: 256 }
    
    validates :description, 
        presence: true, 
        length: { maximum: 256 }
        
end

the-mashmake-blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy] # set_article method will be called before any of the methods specified in `only`
    before_action :require_user, except: [:show, :index]
    before_action :require_same_user_or_admin, except: [:show, :index, :new, :create]
    
    def index
        #byebug # sometimes `byebug` won't stop here. In that case, just restart the puma server
        #@articles = Article.all
        @articles = Article.paginate(page: params[:page], per_page: 5)
    end
    
    def show
    end
    
    def new # Shows the "Create New" form
        @article = Article.new # I have to declare this so that the `form` object in the `_form.html.erb` works
    end
    
    def create # Handles submission from the "Create New" form
        # Typical way of saving the model
        # @article = Article.new
        # @article.title = params[:article][:title]
        # @article.description = params[:article][:description]
        # @article.save
        
        # Shorter way of saving the model by intelligently dealing with params hash
        # IMPORTANT: The `name` attributes used by the form fields in the View layer MUST MATCH the Article class attributes
        # - require(:key1).permit(:key2, :key3) is another way of saying "only get the `:key1` from the `params` hash and only accept/whitelist `:key2` and `:key3` sub-hash from it (any other sub-hashes will be ignored)"
        @article = Article.new(article_params)
        
        @article.user_id = current_user.id # `current_user` method is defined in the ApplicationController
        
        if @article.save
            
            #redirect_to @article # sends to the newly created article page
            
            # Flash is a Rails-provided helper that allows temporarily passing a String, Array or Hash between actions. Once the next action is completely executed, whatever's assigned to this helper is cleared.
            # To eliminate having to write the output of this on every target action (e.g `index` action), this should be implemented in the main layout of the app (app/views/layouts/application.html.erb)
            #flash[:notice] = "Article was saved." 
            flash[:notice] = { successMessage: "Article was saved." } # IMPORTANT: Somehow when this hash is stored into flash[:notice], symbolic keys become string so flash[:notice][:successMessage] is INVALID
            
            redirect_to articles_path # sends to listing (index) - `articles` is the prefix when you run `rails routes` which when appended with `_path`, will yield `/articles` resource path
        else
            # To explain how `@article.errors` exist:
            # - @article is an instance of `Article` model which is a subclass of `ApplicationRecord` which is a subclass of `ActiveRecord::Base`
            # - `ActiveRecord::Base` includes `ActiveRecord::Validations` module
            # - `ActiveRecord::Validations` includes `ActiveRecord::Validations`
            # - `ActiveRecord::Validations` has a method `errors`
            #@error_messages = @article.errors.full_messages 
            #render 'new' # Renders the `new.html.erb` BUT DOES NOT execute the `new` action method above
            
            errorMessages = []
            
            @article.errors.full_messages.each do |msg|
                errorMessages.append("#{msg}")
            end

            flash[:notice] = { errorMessages: errorMessages }
            
            redirect_to new_article_path
        end
        
        #render plain: @article.inspect
    end
    
    def edit # Show the "Edit" form
    end
    
    def update # Handles submission from the "Edit" form
        if @article.update(article_params)
            flash[:notice] = { successMessage: "Article was updated for Article ID: #{@article.id.to_s}" }
            redirect_to articles_path
        else
            errorMessages = []
            
            @article.errors.full_messages.each do |msg|
                errorMessages.append("#{msg} for Article ID: #{@article.id.to_s}")
            end

            flash[:notice] = { errorMessages: errorMessages }
            
            #render 'edit' # this statement doesn't execute the `edit` action above so the flash will end up with the next action method that gets called which is NOT what we wanted
            redirect_to edit_article_path
        end
    end
    
    def destroy
        if @article.destroy
            flash[:notice] = { successMessage: "Article was successfully DELETED for Article ID: #{@article.id.to_s}" }
            redirect_to articles_path
        else
            errorMessages = []
            @article.errors.full_messages.each do |msg|
                errorMessages.append("#{msg} for Article ID: #{@article.id.to_s}")
            end

            flash[:notice] = { errorMessages: errorMessages }
            
            #render 'edit' # this statement doesn't execute the `edit` action above so the flash will end up with the next action method that gets called which is NOT what we wanted
            redirect_to articles_path
        end
        
    end
    
    private # any methods defined after this line are NOT exposed by this class
    
    def set_article
        
        begin # begin..rescue..end is similar to try-catch clause in other programming languages
            @article = Article.find(params[:id])
        rescue ActiveRecord::RecordNotFound => e
            flash[:notice] = { errorMessages: ["Article not found"] }
            redirect_to articles_path
        end
        
    end

    def article_params
        params.require(:article).permit(:title, :description, category_ids: [])
    end
    
    def require_same_user_or_admin
        if current_user != @article.user && !current_user.admin?
            redirect_to root_path
        end
    end
end

the-mashmake-blog/app/views/articles/_articles.html.erb
<div class="container">
<% @articles.each do |article| %>
    <div class="row justify-content-center">
        <div class="col-10 mt-4">
            <div class="card text-center shadow mb-5 bg-white rounded">
              <div class="card-header font-italic">
                by <%= gravatar_for(article.user.email, {size: 20}) %> <%= link_to article.user.username, user_path(article.user) %> (<a href="mailto: <%= article.user.email %>"><%= article.user.email %></a>)
                <br />
                <% if article.categories.any? %>
                  <%= render article.categories %>
                <% end %>
              </div>
              <div class="card-body">
                <h5 class="card-title">
                    <%= link_to article.title, article_path(article), class: 'text-success' %>
                </h5>
                <p class="card-text"><%= truncate(article.description, length: 100) %></p>
                <%= link_to 'View', article_path(article), class: 'btn btn-outline-success' %>
                
                <% if logged_in? && (current_user == article.user || current_user.admin?) %>
                  &nbsp;
                  <%= link_to 'Edit', edit_article_path(article), class: 'btn btn-outline-info' %>
                  &nbsp;
                  <%= link_to 'Delete', article_path(article), class: 'btn btn-outline-danger', method: :delete, data: { confirm: "Are you sure?" } %>
                <% end %>
              </div>
              <div class="card-footer text-muted">
                  <small>
                      Created <%= time_ago_in_words(article.created_at) %> ago, edited <%= time_ago_in_words(article.updated_at) %>  ago
                  </small>
              </div>
            </div>
        </div>
    </div>
<% end %>
<% if @articles.count == 0 %>
  <div class="font-italic text-center">No articles found</div>
<% end %>

  <div class="text-center">
    <%= will_paginate @articles, class: "apple_pagination" %>
  </div>
</div>

the-mashmake-blog/app/views/articles/_form.html.erb
<% 
    # `form_with` is a view helper that provides a way to submit on a form
    # - It automatically embeds a `hidden input` field for `authenticity token` which is a Rails-specific feature
    #   to prevent form submission from unwanted clients
    # - Having the `model: @article` param makes it a candidate for partial as it's using an instance variable as opposed to using `scope: :article` (see commented code at new.html.erb)
%>
<div class="container">
    
    <div class="row justify-content-center">
        <div class="col-12">
            <%= form_with(model: @article, class: "shadow p-5 mb-5 bg-white rounded", local: true) do |form| %>
                
                <div class="form-group row">
                    <%= form.label :title, "Title:", class: "col-sm-2 col-form-label" %>
                    <div class="col-sm-10">
                        <%= form.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article", autofocus: true %>
                    </div>
                </div>
            
                <div class="form-group row">
                    <%= form.label :description, "Description:", class: "col-sm-2 col-form-label" %>
                    <div class="col-sm-10">
                        <%= form.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of article" %>
                    </div>
                </div>
                
                <div class="form-group row">
                    <%= form.label :categories, "Categories:", class: "col-sm-2 col-form-label" %>
                    <div class="col-sm-10">
                        <%= form.collection_select(:category_ids, Category.all, :id, :name, {prompt: "--- Select categories ---"}, {multiple: true, size: 10, class: "custom-select shadow rounded"}) %>
                    </div>
                </div>
                
                <div class="form-group row justify-content-center">
                    <%= form.submit class: "btn btn-outline-primary"%>
                    &nbsp;&nbsp;&nbsp;
                    <%= link_to "Cancel", articles_path, class: "btn btn-outline-danger" %>
                </div>
                
            <% end %>
        </div>
    </div>
</div>

the-mashmake-blog/app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Update Article ID: <%= @article.id %></h1>

<%= render 'form' %>

the-mashmake-blog/app/views/articles/index.html.erb
<h1 class="text-center mt-4">List of Articles</h1>

<%= render 'articles' %>

the-mashmake-blog/app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create new Article</h1>

<% 
    # `form_with` is a view helper that provides a way to submit on a form
    # - It automatically embeds a `hidden input` field for `authenticity token` which is a Rails-specific feature
    #   to prevent form submission from unwanted clients
%>
<!--
<%= form_with scope: :article, url: articles_path, local: true do |form| %>
    <div>
        <%= form.label :title, "Title:" %>
        <br />
        <%= form.text_field :title %>
    </div>
    <br />
    <div>
        <%= form.label :description, "Description:" %>
        <br />
        <%= form.text_area :description, size: "30x10" %>
    </div>
    <div>
        <%= form.submit "Create" %>
    </div>
<% end %>
-->
<%= render 'form' %>

the-mashmake-blog/app/views/articles/show.html.erb
<div class="container">
    <h1 class="text-center mt-4">
        <%= @article.title %>
    </h1>
    <div class="row justify-content-center">
        <div class="col-10 mt-4">
            <div class="card text-center shadow mb-5 bg-white rounded">
              <div class="card-header font-italic">
                by <%= gravatar_for(@article.user.email, {size: 20}) %> <%= link_to @article.user.username, user_path(@article.user) %> (<a href="mailto: <%= @article.user.email %>"><%= @article.user.email %></a>)
                <br />
                <% if @article.categories.any? %>
                  <!-- # Iterates @article.categories and renders categories/_category.html.erb for each iteration, passing `category` object -->
                  <%= render @article.categories %>
                <% end %>
              </div>
              <div class="card-body">
                
                <div class="card-text text-left"><%= simple_format(@article.description) %></div>
                
                <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
                  <%= link_to 'Edit', edit_article_path(@article), class: 'btn btn-outline-info' %>
                  &nbsp;
                  <%= link_to 'Delete', article_path(@article), class: 'btn btn-outline-danger', method: :delete, data: { confirm: "Are you sure?" } %>
                <% end %>
                
              </div>
              <div class="card-footer text-muted">
                  <small>
                      Created <%= time_ago_in_words(@article.created_at) %> ago, edited <%= time_ago_in_words(@article.updated_at) %>  ago
                  </small>
              </div>
            </div>
        </div>
    </div>
</div>